replicaCount: 1

service:
  port: 8090
  targetPort: 8090
  type: ClusterIP

image:
  billingRepository: ghcr.io/solo157/restfull-billing
  tag: latest
  pullPolicy: Always

app:
  billingContainerPort: 8090
  billingHealthPath: /billing/health