replicaCount: 1

image:
  authRepository: auth-service
  repository: kuber-crud-app
  tag: latest
  pullPolicy: Never

service:
  port: 8090
  targetPort: 8090
  type: ClusterIP

app:
  authContainerPort: 8090
  containerPort: 8090
  authHealthPath: /auth/health
  healthPath: /api/health

ingress:
  enabled: true
  className: nginx
  host: arch.homework
  path: /
  apiPath: /api

config:
  DB_URL: production

database:
  secretName: grafana-kuber-app-secret

metrics:
  port: 8091
  path: /actuator/prometheus
