apiVersion: v1
kind: Service
metadata:
  namespace: auth-kuber-service-space
  name: {{ include "delivery-service.name" . }}-service
spec:
  selector:
    app: {{ include "delivery-service.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
