apiVersion: v2
name: auth-validate
description: Helm chart for auth-validate
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common-lib
    repository: "file://../common-lib"
    version: "0.1.0"